### ISSUE TITLE
Relation Extraction Task

### ISSUE THREAD

**Issue by nataliaElv** [argilla-io/roadmap#32]
### Summary
_Summarize the functionality or added value of the feature:_

Support the annotation of relations between entities / spans.

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

- Annotate relationships between entities.
- Allow multiple relations with different names, for example for dependency parsing.
- Indicate the direction of the relationship (source and destination).

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- Add the possibility to draw relations between spans in the Token Classification question.

### Further context
_Add any additional information or details needed to understand the feature:_

```[tasklist]
### Related issues
- [ ] https://github.com/argilla-io/argilla/issues/1839
```

**Comment by jackboyla** [comment]
hi, is there a reason why this is no longer planned? Supporting RE would be a very valuable feature imo

**Comment by davidberenstein1957** [comment]
Hi @jackboyla thanks for the engagement and enthusiasm surrounding this feature. We always try to satisfy as many people as possible but we always have to make a trade-off between various aspect like development-time and community members reached. Not having this feature within the direct roadmap does not mean we will never cover it but it means we don't plan on working on it in the foreseeable feature because there are other more general and fundamental things we feel that have a broader impact on the company. It will help us to prioritise any issues by reacting on the GitHub items so we would love to hear your thoughts on the matter still: https://github.com/argilla-io/argilla/issues/1839. I hope you understand the decision making process a bit better now :)

**Comment by jackboyla** [comment]
@davidberenstein1957 Hi David, totally understand - it’s impossible to do everything :) thanks for the update! Enjoying Argilla too😊
